name: recipe_book
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider:
  dio:
  retrofit:
  json_annotation:
  shimmer:
  fluent_ui:
  supabase_flutter:
  shared_preferences:
  app_links:

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  retrofit_generator:
  json_serializable:

flutter:

  uses-material-design: true

  assets:
    - assets/images/splash.jpg
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
